/** Common IANA timezones for property settings (extend as needed). */
export const HOTEL_TIMEZONES: { value: string; label: string }[] = [
  { value: "UTC", label: "UTC" },
  { value: "America/New_York", label: "America / New York" },
  { value: "America/Chicago", label: "America / Chicago" },
  { value: "America/Los_Angeles", label: "America / Los Angeles" },
  { value: "America/Denver", label: "America / Denver" },
  { value: "America/Toronto", label: "America / Toronto" },
  { value: "America/Sao_Paulo", label: "America / São Paulo" },
  { value: "Europe/London", label: "Europe / London" },
  { value: "Europe/Paris", label: "Europe / Paris" },
  { value: "Europe/Berlin", label: "Europe / Berlin" },
  { value: "Europe/Madrid", label: "Europe / Madrid" },
  { value: "Asia/Dubai", label: "Asia / Dubai" },
  { value: "Asia/Riyadh", label: "Asia / Riyadh" },
  { value: "Asia/Singapore", label: "Asia / Singapore" },
  { value: "Asia/Tokyo", label: "Asia / Tokyo" },
  { value: "Asia/Bangkok", label: "Asia / Bangkok" },
  { value: "Australia/Sydney", label: "Australia / Sydney" },
  { value: "Pacific/Auckland", label: "Pacific / Auckland" },
  { value: "Africa/Cairo", label: "Africa / Cairo" },
  { value: "Africa/Johannesburg", label: "Africa / Johannesburg" },
];

export const HOTEL_CURRENCIES: { value: string; label: string }[] = [
  { value: "ETB", label: "ETB — Ethiopian birr" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British pound" },
  { value: "AED", label: "AED — UAE dirham" },
  { value: "SAR", label: "SAR — Saudi riyal" },
  { value: "EGP", label: "EGP — Egyptian pound" },
  { value: "JPY", label: "JPY — Japanese yen" },
  { value: "SGD", label: "SGD — Singapore dollar" },
  { value: "AUD", label: "AUD — Australian dollar" },
  { value: "CAD", label: "CAD — Canadian dollar" },
  { value: "CHF", label: "CHF — Swiss franc" },
  { value: "BHD", label: "BHD — Bahraini dinar" },
  { value: "KWD", label: "KWD — Kuwaiti dinar" },
  { value: "QAR", label: "QAR — Qatari riyal" },
];
